# Generated by Django 2.2.6 on 2019-10-08 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phclass',
            old_name='age_group',
            new_name='ageGroup',
        ),
    ]
