# Generated by Django 2.2.6 on 2019-10-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20191008_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phclass',
            name='facilitator',
        ),
        migrations.AddField(
            model_name='phclass',
            name='class_designation',
            field=models.CharField(default='CLASS A', max_length=64),
        ),
        migrations.AddField(
            model_name='phclass',
            name='max_age',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='phclass',
            name='min_age',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='phclass',
            name='name',
            field=models.CharField(default='N/A', max_length=64),
        ),
    ]
