# Generated by Django 2.2.6 on 2019-10-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='childName',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='isPresent',
            field=models.BooleanField(default=False),
        ),
    ]
