# Generated by Django 2.2.6 on 2019-10-09 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20191009_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='phClass',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classes.PhClass'),
        ),
    ]
