# Generated by Django 2.2.6 on 2019-10-15 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_child_attendace'),
        ('attendance', '0002_auto_20191010_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Child'),
        ),
    ]
