# Generated by Django 2.2.6 on 2019-10-09 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20191009_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='phClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.PhClass'),
        ),
    ]
